const shopActionType = {
    FETCH_COLLECTIONs_START : 'FETCH_COLLECTIONs_START',
    FETCH_COLLECTIONs_SUCCESS : 'FETCH_COLLECTIONs_SUCCESS',
    FETCH_COLLECTIONs_FAILUR : 'FETCH_COLLECTIONs_FAILUR'
};

export default shopActionType;